// SPDX-License-Identifier: AGPL-3.0-or-later
// Package mihomo renders routing configuration from an authenticated ACL.
// Routing does not replace the gateway's authorization checks.
package mihomo

import (
	"context"
	"errors"
	"fmt"
	"net/netip"
	"sort"
	"strconv"
	"strings"
	"time"

	"securelink2socks/internal/acl"
	"securelink2socks/internal/storage"
)

type Options struct {
	Remote      netip.AddrPort
	Listen      netip.AddrPort
	GeneratedAt time.Time
	Fragment    bool
}

// Render is deterministic for the same snapshot and options, independent of
// server rule order and duplicates. It never accepts credentials or raw PUSH.
func Render(policy *acl.Snapshot, opt Options) ([]byte, error) {
	entries := policy.Entries()
	if len(entries) == 0 {
		return nil, errors.New("cannot export an empty ACL")
	}
	if !opt.Remote.IsValid() || !opt.Remote.Addr().Is4() || opt.Remote.Port() == 0 {
		return nil, errors.New("invalid VPN remote")
	}
	if !opt.Listen.IsValid() || opt.Listen.Addr() != netip.MustParseAddr("127.0.0.1") || opt.Listen.Port() == 0 {
		return nil, errors.New("SOCKS listener must be 127.0.0.1 with a nonzero port")
	}
	if opt.GeneratedAt.IsZero() {
		return nil, errors.New("missing generation time")
	}
	allows, guards := map[string]bool{}, map[string]bool{}
	alias := false
	for _, e := range entries {
		addEntry(allows, guards, e)
		// Explicit XMU service alias, not an inferred DNS/IP authorization.
		if e.Domain == "ip.xmu.edu.cn" || (strings.HasPrefix(e.Domain, "*.") && strings.HasSuffix("ip.xmu.edu.cn", e.Domain[1:])) {
			alias = true
			addEntry(allows, guards, acl.Entry{Domain: "ip4.xmu.edu.cn", Port: e.Port})
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by securelink2socks at %s\n", opt.GeneratedAt.UTC().Format(time.RFC3339))
	b.WriteString("# Account-specific routing snapshot; regenerate after account, ACL, gateway or listener changes.\n# Import/reload explicitly. This file contains no session credentials.\n")
	if opt.Fragment {
		b.WriteString("# MERGE FRAGMENT: append proxies/hosts; PREPEND these rules before existing rules.\n# Keep mode: rule and find-process-mode: always. Preserve domain names for SOCKS.\n# No MATCH rule: retain your existing public-internet policy.\n")
	} else {
		b.WriteString(fullHeader)
	}
	if alias {
		b.WriteString("hosts:\n  ip4.xmu.edu.cn: ip.xmu.edu.cn\n")
	}
	fmt.Fprintf(&b, "proxies:\n  - name: XMU\n    type: socks5\n    server: 127.0.0.1\n    port: %d\n    udp: false\nrules:\n", opt.Listen.Port())
	// These are deliberate routing exceptions, separate from ACL grants.
	b.WriteString("  # Control plane, authentication and loop prevention take precedence.\n")
	for _, rule := range []string{
		"PROCESS-NAME,securelink2socks.exe,DIRECT", "PROCESS-NAME,securelink2socks,DIRECT",
		"DOMAIN,svpnlink.xmu.edu.cn,DIRECT", "DOMAIN,svpnsso.xmu.edu.cn,DIRECT", "DOMAIN,ids.xmu.edu.cn,DIRECT",
		"IP-CIDR," + opt.Remote.Addr().String() + "/32,DIRECT,no-resolve", "IP-CIDR,127.0.0.0/8,DIRECT,no-resolve",
	} {
		emit(&b, rule)
	}
	b.WriteString("  # All ACL grants precede guards, including overlapping prefixes/domains.\n")
	for _, r := range sortedKeys(allows) {
		emit(&b, r)
	}
	b.WriteString("  # Deny other ports and UDP for known resources; never fall through to public rules.\n")
	for _, r := range sortedKeys(guards) {
		emit(&b, r)
	}
	emit(&b, "DOMAIN-SUFFIX,xmu.edu.cn,REJECT")
	if !opt.Fragment {
		emit(&b, "MATCH,DIRECT")
	}
	return []byte(b.String()), nil
}

func addEntry(allows, guards map[string]bool, e acl.Entry) {
	var destination string
	switch {
	case e.Prefix.IsValid():
		destination = "IP-CIDR," + e.Prefix.String() + ",no-resolve"
	case strings.HasPrefix(e.Domain, "*."):
		domain := strings.TrimPrefix(e.Domain, "*.")
		// DOMAIN-SUFFIX includes the apex; SecureLink's wildcard does not.
		destination = "AND,((DOMAIN-SUFFIX," + domain + "),(NOT,((DOMAIN," + domain + "))))"
	default:
		destination = "DOMAIN," + e.Domain
	}
	parts := "(" + destination + "),(NETWORK,TCP)"
	if e.Port != 0 {
		parts += ",(DST-PORT," + strconv.Itoa(int(e.Port)) + ")"
	}
	allows["AND,("+parts+"),XMU"] = true
	// Wrap even simple conditions so IP no-resolve stays inside its rule.
	guards["AND,(("+destination+")),REJECT"] = true
}

func sortedKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
func emit(b *strings.Builder, rule string) { fmt.Fprintf(b, "  - %s\n", strconv.Quote(rule)) }

// Write renders first, then replaces the destination through a same-directory
// temporary file. Invalid policy/cancellation leaves any previous file intact.
func Write(ctx context.Context, path string, policy *acl.Snapshot, opt Options) error {
	data, err := Render(policy, opt)
	if err != nil {
		return err
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	return storage.Write(path, data)
}

const fullHeader = `mixed-port: 7890
allow-lan: false
bind-address: 127.0.0.1
mode: rule
log-level: info
ipv6: false
find-process-mode: always
tun:
  enable: false
sniffer:
  enable: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  use-hosts: true
  respect-rules: false
  nameserver:
    - https://223.5.5.5/dns-query
  direct-nameserver:
    - https://223.5.5.5/dns-query
`
